apiVersion: v1
kind: Service
metadata:
  name: Spring-boot-app-service
  namespace: default

spec:
  selector:
    app: spring-boot-app
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 8080
      nodePort: 32000
      protocol: TCP

